'use strict';

const SDK_STATES = Object.freeze({
  UNLOADED: 'UNLOADED',
  RUNTIME_READY: 'RUNTIME_READY',
  LOADED: 'LOADED',
  INITIALIZING: 'INITIALIZING',
  INITIALIZED: 'INITIALIZED',
  LOGGING_IN: 'LOGGING_IN',
  LOGGED_IN: 'LOGGED_IN',
  LOGGING_OUT: 'LOGGING_OUT',
  UNINITIALIZING: 'UNINITIALIZING',
  RELEASED: 'RELEASED',
  ERROR: 'ERROR'
});

const transitions = Object.freeze({
  [SDK_STATES.UNLOADED]: [SDK_STATES.RUNTIME_READY, SDK_STATES.ERROR],
  [SDK_STATES.RUNTIME_READY]: [SDK_STATES.LOADED, SDK_STATES.ERROR],
  [SDK_STATES.LOADED]: [SDK_STATES.INITIALIZING, SDK_STATES.RELEASED, SDK_STATES.ERROR],
  [SDK_STATES.INITIALIZING]: [SDK_STATES.INITIALIZED, SDK_STATES.ERROR],
  [SDK_STATES.INITIALIZED]: [SDK_STATES.LOGGING_IN, SDK_STATES.UNINITIALIZING, SDK_STATES.ERROR],
  [SDK_STATES.LOGGING_IN]: [SDK_STATES.LOGGED_IN, SDK_STATES.INITIALIZED, SDK_STATES.ERROR],
  [SDK_STATES.LOGGED_IN]: [SDK_STATES.LOGGING_OUT, SDK_STATES.UNINITIALIZING, SDK_STATES.ERROR],
  [SDK_STATES.LOGGING_OUT]: [SDK_STATES.INITIALIZED, SDK_STATES.ERROR],
  [SDK_STATES.UNINITIALIZING]: [SDK_STATES.RELEASED, SDK_STATES.ERROR],
  [SDK_STATES.RELEASED]: [SDK_STATES.RUNTIME_READY, SDK_STATES.ERROR],
  [SDK_STATES.ERROR]: [SDK_STATES.UNLOADED, SDK_STATES.RELEASED]
});

class SdkStateMachine {
  constructor(initialState = SDK_STATES.UNLOADED) {
    this.state = initialState;
  }

  canTransition(nextState) {
    return transitions[this.state].includes(nextState);
  }

  transition(nextState) {
    if (!this.canTransition(nextState)) {
      throw new Error(`非法 SDK 状态转换：${this.state} -> ${nextState}`);
    }
    this.state = nextState;
    return this.state;
  }
}

module.exports = { SDK_STATES, SdkStateMachine, transitions };
